/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto_tbd1;

import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Victo
 */
public class Log_In extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Log_In() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Teoría de Base de Datos I");
        this.pack();
        MainScreen();

        Sign_In.setLocationRelativeTo(this);
        Sign_In.pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Sign_In = new javax.swing.JFrame();
        Fondo1 = new javax.swing.JPanel();
        Real_Estate1 = new javax.swing.JPanel();
        Dreams1 = new javax.swing.JLabel();
        Discover1 = new javax.swing.JLabel();
        Real1 = new javax.swing.JLabel();
        Estate1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        TXT_Abajo = new javax.swing.JLabel();
        Bienvenido1 = new javax.swing.JLabel();
        User1 = new javax.swing.JLabel();
        Username1 = new javax.swing.JTextField();
        Pass2 = new javax.swing.JLabel();
        jPasswordField2 = new javax.swing.JPasswordField();
        LogIN1 = new javax.swing.JLabel();
        Sign1 = new javax.swing.JButton();
        Mostrar_Pass1 = new javax.swing.JCheckBox();
        Login_Background1 = new javax.swing.JLabel();
        Arrow = new javax.swing.JLabel();
        Lines5 = new javax.swing.JLabel();
        Lines6 = new javax.swing.JLabel();
        Lines7 = new javax.swing.JLabel();
        Lines8 = new javax.swing.JLabel();
        Background1 = new javax.swing.JLabel();
        Main_Screen = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        OptionPanel = new javax.swing.JPanel();
        Options = new javax.swing.JLabel();
        AddPanel = new javax.swing.JPanel();
        Add = new javax.swing.JLabel();
        List_Panel = new javax.swing.JPanel();
        List = new javax.swing.JLabel();
        SearchPanel = new javax.swing.JPanel();
        Search = new javax.swing.JLabel();
        ExitPanel = new javax.swing.JPanel();
        Exit2 = new javax.swing.JLabel();
        Real3 = new javax.swing.JLabel();
        State = new javax.swing.JLabel();
        ListPanel = new javax.swing.JLabel();
        SmallHouse = new javax.swing.JLabel();
        Fondo = new javax.swing.JPanel();
        Real_Estate = new javax.swing.JPanel();
        Dreams = new javax.swing.JLabel();
        Discover = new javax.swing.JLabel();
        Real = new javax.swing.JLabel();
        Estate = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        DeNuevo = new javax.swing.JLabel();
        Bienvenido = new javax.swing.JLabel();
        User = new javax.swing.JLabel();
        Username = new javax.swing.JTextField();
        Pass = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        LogIN = new javax.swing.JLabel();
        Log = new javax.swing.JButton();
        SignIn = new javax.swing.JLabel();
        Sign = new javax.swing.JButton();
        Exit = new javax.swing.JLabel();
        Pass1 = new javax.swing.JLabel();
        Mostrar_Pass = new javax.swing.JCheckBox();
        Login_Background = new javax.swing.JLabel();
        Lines1 = new javax.swing.JLabel();
        Lines2 = new javax.swing.JLabel();
        Lines3 = new javax.swing.JLabel();
        Lines4 = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        Sign_In.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        Sign_In.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Fondo1.setBackground(new java.awt.Color(255, 255, 255));
        Fondo1.setForeground(new java.awt.Color(255, 255, 255));
        Fondo1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Real_Estate1.setBackground(new java.awt.Color(255, 255, 255));
        Real_Estate1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Dreams1.setFont(new java.awt.Font("British Shorthair", 0, 80)); // NOI18N
        Dreams1.setForeground(new java.awt.Color(0, 0, 0));
        Dreams1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Dreams1.setText("dreams");
        Real_Estate1.add(Dreams1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, 280, -1));

        Discover1.setFont(new java.awt.Font("Neo Sans Std", 0, 30)); // NOI18N
        Discover1.setForeground(new java.awt.Color(0, 153, 51));
        Discover1.setText("Discover the House of your...");
        Real_Estate1.add(Discover1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        Real1.setFont(new java.awt.Font("British Shorthair", 1, 110)); // NOI18N
        Real1.setForeground(new java.awt.Color(0, 0, 0));
        Real1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Real1.setText("Real");
        Real_Estate1.add(Real1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 240, -1));

        Estate1.setFont(new java.awt.Font("Neo Sans Std", 1, 100)); // NOI18N
        Estate1.setForeground(new java.awt.Color(102, 204, 0));
        Estate1.setText("Estate");
        Real_Estate1.add(Estate1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, -1, -1));

        jSeparator2.setBackground(new java.awt.Color(153, 153, 153));
        Real_Estate1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 550, 20));

        Fondo1.add(Real_Estate1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 590, 380));

        TXT_Abajo.setFont(new java.awt.Font("British Shorthair", 0, 70)); // NOI18N
        TXT_Abajo.setForeground(new java.awt.Color(51, 153, 0));
        TXT_Abajo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TXT_Abajo.setText("a esta aventura!");
        Fondo1.add(TXT_Abajo, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 10, 380, 120));

        Bienvenido1.setBackground(new java.awt.Color(0, 0, 0));
        Bienvenido1.setFont(new java.awt.Font("Neo Sans Std", 1, 48)); // NOI18N
        Bienvenido1.setForeground(new java.awt.Color(51, 51, 51));
        Bienvenido1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Bienvenido1.setText("BIENVENIDO");
        Fondo1.add(Bienvenido1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 0, 390, 70));

        User1.setFont(new java.awt.Font("Neo Sans Std Light", 0, 24)); // NOI18N
        User1.setForeground(new java.awt.Color(51, 51, 51));
        User1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        User1.setText("USERNAME");
        Fondo1.add(User1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 330, 140, 40));

        Username1.setFont(new java.awt.Font("Neo Sans Std Light", 0, 18)); // NOI18N
        Username1.setText("Ingrese su Usuario");
        Username1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Username1MouseClicked(evt);
            }
        });
        Username1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Username1ActionPerformed(evt);
            }
        });
        Fondo1.add(Username1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 360, 330, 40));

        Pass2.setFont(new java.awt.Font("Neo Sans Std Light", 0, 24)); // NOI18N
        Pass2.setForeground(new java.awt.Color(51, 51, 51));
        Pass2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Pass2.setText("PASSWORD");
        Pass2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Pass2MouseClicked(evt);
            }
        });
        Fondo1.add(Pass2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 410, 140, 40));

        jPasswordField2.setFont(new java.awt.Font("Neo Sans Std Light", 0, 18)); // NOI18N
        jPasswordField2.setText("jPasswordField1");
        jPasswordField2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPasswordField2MouseClicked(evt);
            }
        });
        jPasswordField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField2ActionPerformed(evt);
            }
        });
        Fondo1.add(jPasswordField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 440, 330, 40));

        LogIN1.setBackground(new java.awt.Color(0, 0, 0));
        LogIN1.setFont(new java.awt.Font("Neo Sans Std", 1, 28)); // NOI18N
        LogIN1.setForeground(new java.awt.Color(0, 0, 0));
        LogIN1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LogIN1.setText("Log In");
        LogIN1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Fondo1.add(LogIN1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 520, 100, 50));

        Sign1.setBackground(new java.awt.Color(102, 204, 0));
        Sign1.setFont(new java.awt.Font("Neo Sans Std", 1, 24)); // NOI18N
        Sign1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Sign1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Sign1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Sign1MouseClicked(evt);
            }
        });
        Sign1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sign1ActionPerformed(evt);
            }
        });
        Fondo1.add(Sign1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 520, 330, 40));

        Mostrar_Pass1.setFont(new java.awt.Font("Neo Sans Std Light", 0, 14)); // NOI18N
        Mostrar_Pass1.setForeground(new java.awt.Color(102, 102, 102));
        Mostrar_Pass1.setText("Mostrar Contraseña");
        Mostrar_Pass1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mostrar_Pass1ActionPerformed(evt);
            }
        });
        Fondo1.add(Mostrar_Pass1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 480, 150, 30));

        Login_Background1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/Login_Back.png"))); // NOI18N
        Login_Background1.setOpaque(true);
        Fondo1.add(Login_Background1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, -10, 390, 590));

        Arrow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/arrow-symbol.png"))); // NOI18N
        Arrow.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Arrow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ArrowMouseClicked(evt);
            }
        });
        Fondo1.add(Arrow, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 70, 60));

        Lines5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/Abstract Lines.png"))); // NOI18N
        Fondo1.add(Lines5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, 660, 100));

        Lines6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/Abstract Lines.png"))); // NOI18N
        Fondo1.add(Lines6, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 480, 660, 100));

        Lines7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/Abstract Lines.png"))); // NOI18N
        Fondo1.add(Lines7, new org.netbeans.lib.awtextra.AbsoluteConstraints(-230, 480, 660, 100));

        Lines8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/Abstract Lines.png"))); // NOI18N
        Fondo1.add(Lines8, new org.netbeans.lib.awtextra.AbsoluteConstraints(-280, 0, 720, 100));

        Background1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/Fondo.png"))); // NOI18N
        Fondo1.add(Background1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 580));

        Sign_In.getContentPane().add(Fondo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Main_Screen.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 500, 370, 120));

        jPanel3.setBackground(new java.awt.Color(255, 0, 0));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        OptionPanel.setBackground(new java.awt.Color(255, 0, 0));
        OptionPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                OptionPanelMouseExited(evt);
            }
        });

        Options.setBackground(new java.awt.Color(255, 255, 255));
        Options.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Options.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/Option_Menu.png"))); // NOI18N
        Options.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Options.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OptionsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                OptionsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                OptionsMouseExited(evt);
            }
        });

        javax.swing.GroupLayout OptionPanelLayout = new javax.swing.GroupLayout(OptionPanel);
        OptionPanel.setLayout(OptionPanelLayout);
        OptionPanelLayout.setHorizontalGroup(
            OptionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, OptionPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Options, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        OptionPanelLayout.setVerticalGroup(
            OptionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OptionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Options, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.add(OptionPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 110, 90));

        AddPanel.setBackground(new java.awt.Color(255, 0, 0));
        AddPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AddPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AddPanelMouseExited(evt);
            }
        });

        Add.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/rebautizar.png"))); // NOI18N
        Add.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AddMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout AddPanelLayout = new javax.swing.GroupLayout(AddPanel);
        AddPanel.setLayout(AddPanelLayout);
        AddPanelLayout.setHorizontalGroup(
            AddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Add, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
        );
        AddPanelLayout.setVerticalGroup(
            AddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Add, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );

        jPanel3.add(AddPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 110, 80));

        List_Panel.setBackground(new java.awt.Color(255, 0, 0));
        List_Panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                List_PanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                List_PanelMouseExited(evt);
            }
        });

        List.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        List.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/portapapeles.png"))); // NOI18N
        List.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout List_PanelLayout = new javax.swing.GroupLayout(List_Panel);
        List_Panel.setLayout(List_PanelLayout);
        List_PanelLayout.setHorizontalGroup(
            List_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
            .addGroup(List_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(List_PanelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(List, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        List_PanelLayout.setVerticalGroup(
            List_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(List_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(List_PanelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(List, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel3.add(List_Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 110, 100));

        SearchPanel.setBackground(new java.awt.Color(255, 0, 0));
        SearchPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SearchPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SearchPanelMouseExited(evt);
            }
        });

        Search.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/buscar.png"))); // NOI18N
        Search.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout SearchPanelLayout = new javax.swing.GroupLayout(SearchPanel);
        SearchPanel.setLayout(SearchPanelLayout);
        SearchPanelLayout.setHorizontalGroup(
            SearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
            .addGroup(SearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(SearchPanelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Search, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        SearchPanelLayout.setVerticalGroup(
            SearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
            .addGroup(SearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(SearchPanelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Search, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel3.add(SearchPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 110, 90));

        ExitPanel.setBackground(new java.awt.Color(255, 0, 0));

        Exit2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Exit2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/cerrar-sesion.png"))); // NOI18N
        Exit2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Exit2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Exit2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Exit2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Exit2MouseExited(evt);
            }
        });

        javax.swing.GroupLayout ExitPanelLayout = new javax.swing.GroupLayout(ExitPanel);
        ExitPanel.setLayout(ExitPanelLayout);
        ExitPanelLayout.setHorizontalGroup(
            ExitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
            .addGroup(ExitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ExitPanelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Exit2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        ExitPanelLayout.setVerticalGroup(
            ExitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(ExitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ExitPanelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Exit2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel3.add(ExitPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 570, 110, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 0, 110, 780));

        Real3.setFont(new java.awt.Font("British Shorthair", 1, 90)); // NOI18N
        Real3.setForeground(new java.awt.Color(0, 0, 0));
        Real3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Real3.setText("Real");
        jPanel1.add(Real3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 260, 160));

        State.setFont(new java.awt.Font("Neo Sans Std", 1, 80)); // NOI18N
        State.setForeground(new java.awt.Color(0, 0, 0));
        State.setText("Estate");
        jPanel1.add(State, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 300, 110));

        ListPanel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        ListPanel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/MainScreen_House2.png"))); // NOI18N
        jPanel1.add(ListPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 0, 650, 700));

        SmallHouse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/MainScreen_House2(Small).png"))); // NOI18N
        jPanel1.add(SmallHouse, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 500, 110, 120));

        javax.swing.GroupLayout Main_ScreenLayout = new javax.swing.GroupLayout(Main_Screen.getContentPane());
        Main_Screen.getContentPane().setLayout(Main_ScreenLayout);
        Main_ScreenLayout.setHorizontalGroup(
            Main_ScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        Main_ScreenLayout.setVerticalGroup(
            Main_ScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Main_ScreenLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 696, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Fondo.setBackground(new java.awt.Color(255, 255, 255));
        Fondo.setForeground(new java.awt.Color(255, 255, 255));
        Fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Real_Estate.setBackground(new java.awt.Color(255, 255, 255));
        Real_Estate.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Dreams.setFont(new java.awt.Font("British Shorthair", 0, 80)); // NOI18N
        Dreams.setForeground(new java.awt.Color(0, 0, 0));
        Dreams.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Dreams.setText("dreams");
        Real_Estate.add(Dreams, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, 280, -1));

        Discover.setFont(new java.awt.Font("Neo Sans Std", 0, 30)); // NOI18N
        Discover.setForeground(new java.awt.Color(0, 153, 51));
        Discover.setText("Discover the House of your...");
        Real_Estate.add(Discover, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        Real.setFont(new java.awt.Font("British Shorthair", 1, 110)); // NOI18N
        Real.setForeground(new java.awt.Color(0, 0, 0));
        Real.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Real.setText("Real");
        Real_Estate.add(Real, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 240, -1));

        Estate.setFont(new java.awt.Font("Neo Sans Std", 1, 100)); // NOI18N
        Estate.setForeground(new java.awt.Color(102, 204, 0));
        Estate.setText("Estate");
        Real_Estate.add(Estate, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(153, 153, 153));
        Real_Estate.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 550, 20));

        Fondo.add(Real_Estate, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 590, 380));

        DeNuevo.setFont(new java.awt.Font("British Shorthair", 0, 70)); // NOI18N
        DeNuevo.setForeground(new java.awt.Color(51, 153, 0));
        DeNuevo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DeNuevo.setText("de nuevo!");
        Fondo.add(DeNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 100, 380, 120));

        Bienvenido.setBackground(new java.awt.Color(0, 0, 0));
        Bienvenido.setFont(new java.awt.Font("Neo Sans Std", 1, 48)); // NOI18N
        Bienvenido.setForeground(new java.awt.Color(51, 51, 51));
        Bienvenido.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Bienvenido.setText("BIENVENIDO");
        Fondo.add(Bienvenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 90, 390, 70));

        User.setFont(new java.awt.Font("Neo Sans Std Light", 0, 24)); // NOI18N
        User.setForeground(new java.awt.Color(51, 51, 51));
        User.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        User.setText("USERNAME");
        Fondo.add(User, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 180, 140, 40));

        Username.setFont(new java.awt.Font("Neo Sans Std Light", 0, 18)); // NOI18N
        Username.setText("Ingrese su Usuario");
        Username.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UsernameMouseClicked(evt);
            }
        });
        Username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernameActionPerformed(evt);
            }
        });
        Fondo.add(Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 210, 330, 40));

        Pass.setFont(new java.awt.Font("Neo Sans Std Light", 0, 24)); // NOI18N
        Pass.setForeground(new java.awt.Color(51, 51, 51));
        Pass.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Pass.setText("PASSWORD");
        Fondo.add(Pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 260, 140, 40));

        jPasswordField1.setFont(new java.awt.Font("Neo Sans Std Light", 0, 18)); // NOI18N
        jPasswordField1.setText("jPasswordField1");
        jPasswordField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPasswordField1MouseClicked(evt);
            }
        });
        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        Fondo.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 290, 330, 40));

        LogIN.setBackground(new java.awt.Color(0, 0, 0));
        LogIN.setFont(new java.awt.Font("Neo Sans Std", 1, 28)); // NOI18N
        LogIN.setForeground(new java.awt.Color(0, 0, 0));
        LogIN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LogIN.setText("Log In");
        LogIN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Fondo.add(LogIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 360, 100, 50));

        Log.setBackground(new java.awt.Color(102, 204, 0));
        Log.setFont(new java.awt.Font("Neo Sans Std", 1, 24)); // NOI18N
        Log.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Log.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Log.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogMouseClicked(evt);
            }
        });
        Log.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogActionPerformed(evt);
            }
        });
        Fondo.add(Log, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 360, 330, 40));

        SignIn.setBackground(new java.awt.Color(0, 0, 0));
        SignIn.setFont(new java.awt.Font("Neo Sans Std", 1, 28)); // NOI18N
        SignIn.setForeground(new java.awt.Color(0, 0, 0));
        SignIn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SignIn.setText("Sign In");
        SignIn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Fondo.add(SignIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 430, 100, 50));

        Sign.setBackground(new java.awt.Color(204, 204, 204));
        Sign.setFont(new java.awt.Font("Neo Sans Std", 1, 24)); // NOI18N
        Sign.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Sign.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Sign.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SignMouseClicked(evt);
            }
        });
        Sign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignActionPerformed(evt);
            }
        });
        Fondo.add(Sign, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 430, 330, 40));

        Exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/cerrar-sesion.png"))); // NOI18N
        Exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ExitMouseExited(evt);
            }
        });
        Fondo.add(Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 500, -1, -1));

        Pass1.setFont(new java.awt.Font("Neo Sans Std Light", 0, 18)); // NOI18N
        Pass1.setForeground(new java.awt.Color(153, 153, 153));
        Pass1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Pass1.setText("No tienes cuenta? Entonces dale Sign In");
        Fondo.add(Pass1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 400, 330, 40));

        Mostrar_Pass.setFont(new java.awt.Font("Neo Sans Std Light", 0, 14)); // NOI18N
        Mostrar_Pass.setForeground(new java.awt.Color(102, 102, 102));
        Mostrar_Pass.setText("Mostrar Contraseña");
        Mostrar_Pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mostrar_PassActionPerformed(evt);
            }
        });
        Fondo.add(Mostrar_Pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 330, 150, 30));

        Login_Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/Login_Back.png"))); // NOI18N
        Login_Background.setOpaque(true);
        Fondo.add(Login_Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 90, 390, 400));

        Lines1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/Abstract Lines.png"))); // NOI18N
        Fondo.add(Lines1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, 660, 100));

        Lines2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/Abstract Lines.png"))); // NOI18N
        Fondo.add(Lines2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 480, 660, 100));

        Lines3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/Abstract Lines.png"))); // NOI18N
        Fondo.add(Lines3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-230, 480, 660, 100));

        Lines4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/Abstract Lines.png"))); // NOI18N
        Fondo.add(Lines4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-280, 0, 720, 100));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/Fondo.png"))); // NOI18N
        Fondo.add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 580));

        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LogActionPerformed

    private void UsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernameActionPerformed

    }//GEN-LAST:event_UsernameActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void jPasswordField1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPasswordField1MouseClicked
        jPasswordField1.setText("");
    }//GEN-LAST:event_jPasswordField1MouseClicked

    private void UsernameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UsernameMouseClicked
        Username.setText("");
    }//GEN-LAST:event_UsernameMouseClicked

    private void SignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SignActionPerformed

    private void SignMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignMouseClicked
        Log_In log = new Log_In();

        log.setVisible(false);
        Sign_In.setVisible(true);
        Sign_In.setLocationRelativeTo(this);
        dispose();
    }//GEN-LAST:event_SignMouseClicked

    private void ExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseClicked
        int showConfirmDialog = JOptionPane.showConfirmDialog(rootPane, "Desea salir del Programa?", "WARNING!", JOptionPane.WARNING_MESSAGE);

        if (showConfirmDialog == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_ExitMouseClicked

    private void ExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseEntered

    }//GEN-LAST:event_ExitMouseEntered

    private void ExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseExited

    }//GEN-LAST:event_ExitMouseExited

    private void LogMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogMouseClicked
        String user = Username.getText();
        String pass = jPasswordField1.getText();

        if (user.equals("")) {
            JOptionPane.showMessageDialog(null, "Inserte su Nombre de Usuario Correctamente");
        } else if (pass.equals("")) {
            JOptionPane.showMessageDialog(null, "Inserte su Contraseña de Usuario Correctamente");
        } else if (user.equals("Admin") && pass.equals("12345")) {
            JOptionPane.showMessageDialog(null, "Succesfull Login", "Login de Administrador", JOptionPane.PLAIN_MESSAGE);
            isAdmin = true;

            Log_In sign = new Log_In();
            sign.setVisible(false);
            Main_Screen.setVisible(true);
            dispose();
        } else if (User_Admin.iniciarSesion(user, pass)) {
            JOptionPane.showMessageDialog(null, "Successfull Login!");

            Log_In sign = new Log_In();
            Main_Screen.setVisible(true);
            sign.setVisible(false);
            dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Usuario o Contraseña Incorectos \nIntentelo de Nuevo", "Incorrect User or Pass", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_LogMouseClicked

    private void Mostrar_PassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mostrar_PassActionPerformed
        if (Mostrar_Pass.isSelected()) {
            jPasswordField1.setEchoChar((char) 0);
        } else {
            jPasswordField1.setEchoChar('*');
        }
    }//GEN-LAST:event_Mostrar_PassActionPerformed

    private void Username1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Username1MouseClicked
        Username.setText("");
    }//GEN-LAST:event_Username1MouseClicked

    private void Username1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Username1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Username1ActionPerformed

    private void jPasswordField2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPasswordField2MouseClicked
        jPasswordField1.setText("");
    }//GEN-LAST:event_jPasswordField2MouseClicked

    private void jPasswordField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField2ActionPerformed

    private void Sign1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Sign1MouseClicked
        Log_In log = new Log_In();
        log.setVisible(false);
        Main_Screen.setVisible(true);
        dispose();
    }//GEN-LAST:event_Sign1MouseClicked

    private void Sign1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sign1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Sign1ActionPerformed

    private void Mostrar_Pass1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mostrar_Pass1ActionPerformed
        if (Mostrar_Pass.isSelected()) {
            jPasswordField1.setEchoChar((char) 0);
        } else {
            jPasswordField1.setEchoChar('*');
        }
    }//GEN-LAST:event_Mostrar_Pass1ActionPerformed

    private void ArrowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ArrowMouseClicked
        Log_In login = new Log_In();

        Sign_In.setVisible(false);
        login.setVisible(true);

        login.setLocationRelativeTo(this);
        dispose();
    }//GEN-LAST:event_ArrowMouseClicked

    private void Pass2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pass2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Pass2MouseClicked

    private void OptionsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OptionsMouseClicked
        boolean isVisible = Add.isVisible() || List.isVisible() || Search.isVisible();

        Add.setVisible(!isVisible);
        List.setVisible(!isVisible);
        Search.setVisible(!isVisible);
    }//GEN-LAST:event_OptionsMouseClicked

    private void OptionsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OptionsMouseEntered
        OptionPanel.setBackground(new Color(139, 0, 0));
    }//GEN-LAST:event_OptionsMouseEntered

    private void OptionsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OptionsMouseExited
        OptionPanel.setBackground(null);
    }//GEN-LAST:event_OptionsMouseExited

    private void OptionPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OptionPanelMouseExited
        //OptionPanel.setBackground(null);
    }//GEN-LAST:event_OptionPanelMouseExited

    private void AddMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddMouseEntered
        AddPanel.setBackground(new Color(139, 0, 0));
    }//GEN-LAST:event_AddMouseEntered

    private void AddPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddPanelMouseEntered
        AddPanel.setBackground(null);
    }//GEN-LAST:event_AddPanelMouseEntered

    private void AddPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddPanelMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_AddPanelMouseExited

    private void List_PanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_List_PanelMouseEntered
        List_Panel.setBackground(new Color(139, 0, 0));
    }//GEN-LAST:event_List_PanelMouseEntered

    private void List_PanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_List_PanelMouseExited
        List_Panel.setBackground(null);
    }//GEN-LAST:event_List_PanelMouseExited

    private void SearchPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchPanelMouseEntered
        SearchPanel.setBackground(new Color(139, 0, 0));
    }//GEN-LAST:event_SearchPanelMouseEntered

    private void SearchPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchPanelMouseExited
        SearchPanel.setBackground(null);
    }//GEN-LAST:event_SearchPanelMouseExited

    private void Exit2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Exit2MouseClicked
        int showConfirmDialog = JOptionPane.showConfirmDialog(rootPane, "Desea salir del Programa?", "WARNING!", JOptionPane.WARNING_MESSAGE);

        if (showConfirmDialog == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_Exit2MouseClicked

    private void Exit2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Exit2MouseEntered
        ExitPanel.setBackground(new Color(139, 0, 0));
    }//GEN-LAST:event_Exit2MouseEntered

    private void Exit2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Exit2MouseExited
        ExitPanel.setBackground(null);
    }//GEN-LAST:event_Exit2MouseExited

    /**
     * @param args the command line arguments
     */
    public void MainScreen() {
        getContentPane().setPreferredSize(Toolkit.getDefaultToolkit().getScreenSize());
        setResizable(false);
        show();
        setLocationRelativeTo(null);
        this.setTitle("Teoría de Base de Datos I");
        Image icono = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("pics/Tiger.jpg"));
        this.setIconImage(icono);

        Add.setVisible(false);
        List.setVisible(false);
        Search.setVisible(false);

        Main_Screen.setExtendedState(MAXIMIZED_BOTH);
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Log_In.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Log_In.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Log_In.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Log_In.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Log_In().setVisible(true);
            }
        });
    }

    boolean isAdmin = false;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Add;
    private javax.swing.JPanel AddPanel;
    private javax.swing.JLabel Arrow;
    private javax.swing.JLabel Background;
    private javax.swing.JLabel Background1;
    private javax.swing.JLabel Bienvenido;
    private javax.swing.JLabel Bienvenido1;
    private javax.swing.JLabel DeNuevo;
    private javax.swing.JLabel Discover;
    private javax.swing.JLabel Discover1;
    private javax.swing.JLabel Dreams;
    private javax.swing.JLabel Dreams1;
    private javax.swing.JLabel Estate;
    private javax.swing.JLabel Estate1;
    private javax.swing.JLabel Exit;
    private javax.swing.JLabel Exit2;
    private javax.swing.JPanel ExitPanel;
    private javax.swing.JPanel Fondo;
    private javax.swing.JPanel Fondo1;
    private javax.swing.JLabel Lines1;
    private javax.swing.JLabel Lines2;
    private javax.swing.JLabel Lines3;
    private javax.swing.JLabel Lines4;
    private javax.swing.JLabel Lines5;
    private javax.swing.JLabel Lines6;
    private javax.swing.JLabel Lines7;
    private javax.swing.JLabel Lines8;
    private javax.swing.JLabel List;
    private javax.swing.JLabel ListPanel;
    private javax.swing.JPanel List_Panel;
    private javax.swing.JButton Log;
    private javax.swing.JLabel LogIN;
    private javax.swing.JLabel LogIN1;
    private javax.swing.JLabel Login_Background;
    private javax.swing.JLabel Login_Background1;
    private javax.swing.JFrame Main_Screen;
    private javax.swing.JCheckBox Mostrar_Pass;
    private javax.swing.JCheckBox Mostrar_Pass1;
    private javax.swing.JPanel OptionPanel;
    private javax.swing.JLabel Options;
    private javax.swing.JLabel Pass;
    private javax.swing.JLabel Pass1;
    private javax.swing.JLabel Pass2;
    private javax.swing.JLabel Real;
    private javax.swing.JLabel Real1;
    private javax.swing.JLabel Real3;
    private javax.swing.JPanel Real_Estate;
    private javax.swing.JPanel Real_Estate1;
    private javax.swing.JLabel Search;
    private javax.swing.JPanel SearchPanel;
    private javax.swing.JButton Sign;
    private javax.swing.JButton Sign1;
    private javax.swing.JLabel SignIn;
    private javax.swing.JFrame Sign_In;
    private javax.swing.JLabel SmallHouse;
    private javax.swing.JLabel State;
    private javax.swing.JLabel TXT_Abajo;
    private javax.swing.JLabel User;
    private javax.swing.JLabel User1;
    private javax.swing.JTextField Username;
    private javax.swing.JTextField Username1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
