/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto_tbd1;

import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Victo
 */
public class Log_In extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Log_In() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Teoría de Base de Datos I");
        Image icono = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("pics/Tiger.jpg"));
        this.setIconImage(icono);
        this.pack();
        MainScreen();

        Sign_In.setLocationRelativeTo(this);
        Sign_In.pack();
        
        MainScreen_Vendedor.setLocationRelativeTo(null);
        MainScreen_Vendedor.pack();
        MainScreen_Vendedor.getContentPane().setPreferredSize(Toolkit.getDefaultToolkit().getScreenSize());
        MainScreen_Vendedor.setExtendedState(MAXIMIZED_BOTH);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Sign_In = new javax.swing.JFrame();
        Fondo1 = new javax.swing.JPanel();
        Real_Estate1 = new javax.swing.JPanel();
        Dreams1 = new javax.swing.JLabel();
        Discover1 = new javax.swing.JLabel();
        Real1 = new javax.swing.JLabel();
        Estate1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        TXT_Abajo = new javax.swing.JLabel();
        Bienvenido1 = new javax.swing.JLabel();
        User1 = new javax.swing.JLabel();
        Username1 = new javax.swing.JTextField();
        Pass2 = new javax.swing.JLabel();
        jPasswordField2 = new javax.swing.JPasswordField();
        LogIN1 = new javax.swing.JLabel();
        Sign1 = new javax.swing.JButton();
        Mostrar_Pass1 = new javax.swing.JCheckBox();
        Login_Background1 = new javax.swing.JLabel();
        Arrow = new javax.swing.JLabel();
        Lines5 = new javax.swing.JLabel();
        Lines6 = new javax.swing.JLabel();
        Lines7 = new javax.swing.JLabel();
        Lines8 = new javax.swing.JLabel();
        Background1 = new javax.swing.JLabel();
        MainScreen_Admin = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        Line = new javax.swing.JPanel();
        Layer = new javax.swing.JPanel();
        Indicator = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        OptionPanel = new javax.swing.JPanel();
        Options = new javax.swing.JLabel();
        MantenimientoPanel = new javax.swing.JPanel();
        Mantenimiento = new javax.swing.JLabel();
        Bitacora_Panel = new javax.swing.JPanel();
        Bitacora = new javax.swing.JLabel();
        Reportes_Panel = new javax.swing.JPanel();
        Reportes = new javax.swing.JLabel();
        ExitPanel = new javax.swing.JPanel();
        Exit2 = new javax.swing.JLabel();
        Real3 = new javax.swing.JLabel();
        State = new javax.swing.JLabel();
        ListPanel = new javax.swing.JLabel();
        SmallHouse = new javax.swing.JLabel();
        Administrador = new javax.swing.JLabel();
        MainScreen_Vendedor = new javax.swing.JFrame();
        jPanel2 = new javax.swing.JPanel();
        Line1 = new javax.swing.JPanel();
        Layer1 = new javax.swing.JPanel();
        Indicator1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        OptionVendedor = new javax.swing.JPanel();
        OptionsVend = new javax.swing.JLabel();
        PropiedadesAsignadas = new javax.swing.JPanel();
        PropAsign = new javax.swing.JLabel();
        PropiedadesVendidas = new javax.swing.JPanel();
        PropVendidas = new javax.swing.JLabel();
        ExitPanel1 = new javax.swing.JPanel();
        Exit3 = new javax.swing.JLabel();
        Real4 = new javax.swing.JLabel();
        State1 = new javax.swing.JLabel();
        ListPanel1 = new javax.swing.JLabel();
        SmallHouse1 = new javax.swing.JLabel();
        Administrador1 = new javax.swing.JLabel();
        MainScreen_Admin2 = new javax.swing.JFrame();
        jPanel5 = new javax.swing.JPanel();
        Line2 = new javax.swing.JPanel();
        Layer2 = new javax.swing.JPanel();
        Indicator2 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        OptionPanel2 = new javax.swing.JPanel();
        Options2 = new javax.swing.JLabel();
        MantenimientoPanel2 = new javax.swing.JPanel();
        Mantenimiento2 = new javax.swing.JLabel();
        Bitacora_Panel2 = new javax.swing.JPanel();
        Bitacora2 = new javax.swing.JLabel();
        Reportes_Panel2 = new javax.swing.JPanel();
        Reportes2 = new javax.swing.JLabel();
        ExitPanel2 = new javax.swing.JPanel();
        Exit4 = new javax.swing.JLabel();
        Real5 = new javax.swing.JLabel();
        State2 = new javax.swing.JLabel();
        ListPanel2 = new javax.swing.JLabel();
        SmallHouse2 = new javax.swing.JLabel();
        Administrador2 = new javax.swing.JLabel();
        Fondo = new javax.swing.JPanel();
        Real_Estate = new javax.swing.JPanel();
        Dreams = new javax.swing.JLabel();
        Discover = new javax.swing.JLabel();
        Real = new javax.swing.JLabel();
        Estate = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        DeNuevo = new javax.swing.JLabel();
        Bienvenido = new javax.swing.JLabel();
        User = new javax.swing.JLabel();
        Username = new javax.swing.JTextField();
        Pass = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        LogIN = new javax.swing.JLabel();
        Log = new javax.swing.JButton();
        SignIn = new javax.swing.JLabel();
        Sign = new javax.swing.JButton();
        Exit = new javax.swing.JLabel();
        Pass1 = new javax.swing.JLabel();
        Mostrar_Pass = new javax.swing.JCheckBox();
        Login_Background = new javax.swing.JLabel();
        Lines1 = new javax.swing.JLabel();
        Lines2 = new javax.swing.JLabel();
        Lines3 = new javax.swing.JLabel();
        Lines4 = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        Sign_In.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        Sign_In.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Fondo1.setBackground(new java.awt.Color(255, 255, 255));
        Fondo1.setForeground(new java.awt.Color(255, 255, 255));
        Fondo1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Real_Estate1.setBackground(new java.awt.Color(255, 255, 255));
        Real_Estate1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Dreams1.setFont(new java.awt.Font("British Shorthair", 0, 80)); // NOI18N
        Dreams1.setForeground(new java.awt.Color(0, 0, 0));
        Dreams1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Dreams1.setText("dreams");
        Real_Estate1.add(Dreams1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, 280, -1));

        Discover1.setFont(new java.awt.Font("Neo Sans Std", 0, 30)); // NOI18N
        Discover1.setForeground(new java.awt.Color(0, 153, 51));
        Discover1.setText("Discover the House of your...");
        Real_Estate1.add(Discover1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        Real1.setFont(new java.awt.Font("British Shorthair", 1, 110)); // NOI18N
        Real1.setForeground(new java.awt.Color(0, 0, 0));
        Real1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Real1.setText("Real");
        Real_Estate1.add(Real1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 240, -1));

        Estate1.setFont(new java.awt.Font("Neo Sans Std", 1, 100)); // NOI18N
        Estate1.setForeground(new java.awt.Color(102, 204, 0));
        Estate1.setText("Estate");
        Real_Estate1.add(Estate1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, -1, -1));

        jSeparator2.setBackground(new java.awt.Color(153, 153, 153));
        Real_Estate1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 550, 20));

        Fondo1.add(Real_Estate1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 590, 380));

        TXT_Abajo.setFont(new java.awt.Font("British Shorthair", 0, 70)); // NOI18N
        TXT_Abajo.setForeground(new java.awt.Color(51, 153, 0));
        TXT_Abajo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TXT_Abajo.setText("a esta aventura!");
        Fondo1.add(TXT_Abajo, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 10, 380, 120));

        Bienvenido1.setBackground(new java.awt.Color(0, 0, 0));
        Bienvenido1.setFont(new java.awt.Font("Neo Sans Std", 1, 48)); // NOI18N
        Bienvenido1.setForeground(new java.awt.Color(51, 51, 51));
        Bienvenido1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Bienvenido1.setText("BIENVENIDO");
        Fondo1.add(Bienvenido1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 0, 390, 70));

        User1.setFont(new java.awt.Font("Neo Sans Std Light", 0, 24)); // NOI18N
        User1.setForeground(new java.awt.Color(51, 51, 51));
        User1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        User1.setText("USERNAME");
        Fondo1.add(User1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 330, 140, 40));

        Username1.setFont(new java.awt.Font("Neo Sans Std Light", 0, 18)); // NOI18N
        Username1.setText("Ingrese su Usuario");
        Username1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Username1MouseClicked(evt);
            }
        });
        Username1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Username1ActionPerformed(evt);
            }
        });
        Fondo1.add(Username1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 360, 330, 40));

        Pass2.setFont(new java.awt.Font("Neo Sans Std Light", 0, 24)); // NOI18N
        Pass2.setForeground(new java.awt.Color(51, 51, 51));
        Pass2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Pass2.setText("PASSWORD");
        Pass2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Pass2MouseClicked(evt);
            }
        });
        Fondo1.add(Pass2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 410, 140, 40));

        jPasswordField2.setFont(new java.awt.Font("Neo Sans Std Light", 0, 18)); // NOI18N
        jPasswordField2.setText("jPasswordField1");
        jPasswordField2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPasswordField2MouseClicked(evt);
            }
        });
        jPasswordField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField2ActionPerformed(evt);
            }
        });
        jPasswordField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordField2KeyPressed(evt);
            }
        });
        Fondo1.add(jPasswordField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 440, 330, 40));

        LogIN1.setBackground(new java.awt.Color(0, 0, 0));
        LogIN1.setFont(new java.awt.Font("Neo Sans Std", 1, 28)); // NOI18N
        LogIN1.setForeground(new java.awt.Color(0, 0, 0));
        LogIN1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LogIN1.setText("Log In");
        LogIN1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Fondo1.add(LogIN1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 520, 100, 50));

        Sign1.setBackground(new java.awt.Color(102, 204, 0));
        Sign1.setFont(new java.awt.Font("Neo Sans Std", 1, 24)); // NOI18N
        Sign1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Sign1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Sign1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Sign1MouseClicked(evt);
            }
        });
        Sign1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sign1ActionPerformed(evt);
            }
        });
        Fondo1.add(Sign1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 520, 330, 40));

        Mostrar_Pass1.setFont(new java.awt.Font("Neo Sans Std Light", 0, 14)); // NOI18N
        Mostrar_Pass1.setForeground(new java.awt.Color(102, 102, 102));
        Mostrar_Pass1.setText("Mostrar Contraseña");
        Mostrar_Pass1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mostrar_Pass1ActionPerformed(evt);
            }
        });
        Fondo1.add(Mostrar_Pass1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 480, 150, 30));

        Login_Background1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/Login_Back.png"))); // NOI18N
        Login_Background1.setOpaque(true);
        Fondo1.add(Login_Background1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, -10, 390, 590));

        Arrow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/arrow-symbol.png"))); // NOI18N
        Arrow.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Arrow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ArrowMouseClicked(evt);
            }
        });
        Fondo1.add(Arrow, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 70, 60));

        Lines5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/Abstract Lines.png"))); // NOI18N
        Fondo1.add(Lines5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, 660, 100));

        Lines6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/Abstract Lines.png"))); // NOI18N
        Fondo1.add(Lines6, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 480, 660, 100));

        Lines7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/Abstract Lines.png"))); // NOI18N
        Fondo1.add(Lines7, new org.netbeans.lib.awtextra.AbsoluteConstraints(-230, 480, 660, 100));

        Lines8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/Abstract Lines.png"))); // NOI18N
        Fondo1.add(Lines8, new org.netbeans.lib.awtextra.AbsoluteConstraints(-280, 0, 720, 100));

        Background1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/Fondo.png"))); // NOI18N
        Fondo1.add(Background1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 580));

        Sign_In.getContentPane().add(Fondo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        MainScreen_Admin.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Line.setBackground(new java.awt.Color(102, 204, 0));
        Line.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(Line, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 40));

        Layer.setBackground(new java.awt.Color(102, 204, 0));
        Layer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Indicator.setBackground(new java.awt.Color(0, 0, 0));
        Indicator.setFont(new java.awt.Font("Neo Sans Std", 0, 60)); // NOI18N
        Indicator.setForeground(new java.awt.Color(255, 255, 255));
        Indicator.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Layer.add(Indicator, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 510, 130));

        jPanel1.add(Layer, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 390, 510, 120));

        jPanel3.setBackground(new java.awt.Color(102, 204, 0));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        OptionPanel.setBackground(new java.awt.Color(102, 204, 0));
        OptionPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                OptionPanelMouseExited(evt);
            }
        });

        Options.setBackground(new java.awt.Color(255, 255, 255));
        Options.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Options.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/Option_Menu.png"))); // NOI18N
        Options.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Options.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OptionsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                OptionsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                OptionsMouseExited(evt);
            }
        });

        javax.swing.GroupLayout OptionPanelLayout = new javax.swing.GroupLayout(OptionPanel);
        OptionPanel.setLayout(OptionPanelLayout);
        OptionPanelLayout.setHorizontalGroup(
            OptionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, OptionPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Options, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        OptionPanelLayout.setVerticalGroup(
            OptionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OptionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Options, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.add(OptionPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 110, 90));

        MantenimientoPanel.setBackground(new java.awt.Color(102, 204, 0));
        MantenimientoPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MantenimientoPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MantenimientoPanelMouseExited(evt);
            }
        });

        Mantenimiento.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Mantenimiento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/rebautizar.png"))); // NOI18N
        Mantenimiento.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Mantenimiento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MantenimientoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MantenimientoMouseExited(evt);
            }
        });

        javax.swing.GroupLayout MantenimientoPanelLayout = new javax.swing.GroupLayout(MantenimientoPanel);
        MantenimientoPanel.setLayout(MantenimientoPanelLayout);
        MantenimientoPanelLayout.setHorizontalGroup(
            MantenimientoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Mantenimiento, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
        );
        MantenimientoPanelLayout.setVerticalGroup(
            MantenimientoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MantenimientoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Mantenimiento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );

        jPanel3.add(MantenimientoPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 110, 80));

        Bitacora_Panel.setBackground(new java.awt.Color(102, 204, 0));
        Bitacora_Panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Bitacora_PanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Bitacora_PanelMouseExited(evt);
            }
        });

        Bitacora.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Bitacora.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/portapapeles.png"))); // NOI18N
        Bitacora.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Bitacora.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BitacoraMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BitacoraMouseExited(evt);
            }
        });

        javax.swing.GroupLayout Bitacora_PanelLayout = new javax.swing.GroupLayout(Bitacora_Panel);
        Bitacora_Panel.setLayout(Bitacora_PanelLayout);
        Bitacora_PanelLayout.setHorizontalGroup(
            Bitacora_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
            .addGroup(Bitacora_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Bitacora_PanelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Bitacora, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        Bitacora_PanelLayout.setVerticalGroup(
            Bitacora_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(Bitacora_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Bitacora_PanelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Bitacora, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel3.add(Bitacora_Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 110, 100));

        Reportes_Panel.setBackground(new java.awt.Color(102, 204, 0));
        Reportes_Panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Reportes_PanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Reportes_PanelMouseExited(evt);
            }
        });

        Reportes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Reportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/buscar.png"))); // NOI18N
        Reportes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Reportes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ReportesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ReportesMouseExited(evt);
            }
        });

        javax.swing.GroupLayout Reportes_PanelLayout = new javax.swing.GroupLayout(Reportes_Panel);
        Reportes_Panel.setLayout(Reportes_PanelLayout);
        Reportes_PanelLayout.setHorizontalGroup(
            Reportes_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Reportes_PanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Reportes, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        Reportes_PanelLayout.setVerticalGroup(
            Reportes_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Reportes_PanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Reportes, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3.add(Reportes_Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 110, 90));

        ExitPanel.setBackground(new java.awt.Color(102, 204, 0));

        Exit2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Exit2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/cerrar-sesion.png"))); // NOI18N
        Exit2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Exit2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Exit2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Exit2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Exit2MouseExited(evt);
            }
        });

        javax.swing.GroupLayout ExitPanelLayout = new javax.swing.GroupLayout(ExitPanel);
        ExitPanel.setLayout(ExitPanelLayout);
        ExitPanelLayout.setHorizontalGroup(
            ExitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
            .addGroup(ExitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ExitPanelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Exit2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        ExitPanelLayout.setVerticalGroup(
            ExitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(ExitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ExitPanelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Exit2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel3.add(ExitPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 570, 110, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 0, 110, 700));

        Real3.setFont(new java.awt.Font("British Shorthair", 0, 150)); // NOI18N
        Real3.setForeground(new java.awt.Color(0, 0, 0));
        Real3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Real3.setText("Real");
        jPanel1.add(Real3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 310, 240));

        State.setFont(new java.awt.Font("Neo Sans Std", 1, 120)); // NOI18N
        State.setForeground(new java.awt.Color(0, 0, 0));
        State.setText("Estate");
        jPanel1.add(State, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, 370, -1));

        ListPanel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        ListPanel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/MainScreen_House2.png"))); // NOI18N
        jPanel1.add(ListPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 0, 650, 700));

        SmallHouse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/MainScreen_House2(Small).png"))); // NOI18N
        jPanel1.add(SmallHouse, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 390, 110, 120));

        Administrador.setFont(new java.awt.Font("Neo Sans Std", 1, 80)); // NOI18N
        Administrador.setForeground(new java.awt.Color(204, 204, 204));
        Administrador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Administrador.setText("Administrador");
        Administrador.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(Administrador, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 560, 590, 110));

        javax.swing.GroupLayout MainScreen_AdminLayout = new javax.swing.GroupLayout(MainScreen_Admin.getContentPane());
        MainScreen_Admin.getContentPane().setLayout(MainScreen_AdminLayout);
        MainScreen_AdminLayout.setHorizontalGroup(
            MainScreen_AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        MainScreen_AdminLayout.setVerticalGroup(
            MainScreen_AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 675, Short.MAX_VALUE)
        );

        MainScreen_Vendedor.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Line1.setBackground(new java.awt.Color(0, 204, 204));
        Line1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(Line1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 40));

        Layer1.setBackground(new java.awt.Color(0, 204, 204));
        Layer1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Indicator1.setBackground(new java.awt.Color(0, 0, 0));
        Indicator1.setFont(new java.awt.Font("Neo Sans Std", 0, 60)); // NOI18N
        Indicator1.setForeground(new java.awt.Color(255, 255, 255));
        Indicator1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Layer1.add(Indicator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 510, 130));

        jPanel2.add(Layer1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 390, 510, 120));

        jPanel4.setBackground(new java.awt.Color(0, 204, 204));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        OptionVendedor.setBackground(new java.awt.Color(0, 204, 204));
        OptionVendedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                OptionVendedorMouseExited(evt);
            }
        });

        OptionsVend.setBackground(new java.awt.Color(255, 255, 255));
        OptionsVend.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        OptionsVend.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/Option_Menu.png"))); // NOI18N
        OptionsVend.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        OptionsVend.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OptionsVendMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                OptionsVendMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                OptionsVendMouseExited(evt);
            }
        });

        javax.swing.GroupLayout OptionVendedorLayout = new javax.swing.GroupLayout(OptionVendedor);
        OptionVendedor.setLayout(OptionVendedorLayout);
        OptionVendedorLayout.setHorizontalGroup(
            OptionVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, OptionVendedorLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(OptionsVend, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        OptionVendedorLayout.setVerticalGroup(
            OptionVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OptionVendedorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(OptionsVend, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel4.add(OptionVendedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 110, 90));

        PropiedadesAsignadas.setBackground(new java.awt.Color(0, 204, 204));
        PropiedadesAsignadas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PropiedadesAsignadasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PropiedadesAsignadasMouseExited(evt);
            }
        });

        PropAsign.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PropAsign.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/portapapeles.png"))); // NOI18N
        PropAsign.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PropAsign.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PropAsignMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PropAsignMouseExited(evt);
            }
        });

        javax.swing.GroupLayout PropiedadesAsignadasLayout = new javax.swing.GroupLayout(PropiedadesAsignadas);
        PropiedadesAsignadas.setLayout(PropiedadesAsignadasLayout);
        PropiedadesAsignadasLayout.setHorizontalGroup(
            PropiedadesAsignadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
            .addGroup(PropiedadesAsignadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PropiedadesAsignadasLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(PropAsign, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        PropiedadesAsignadasLayout.setVerticalGroup(
            PropiedadesAsignadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(PropiedadesAsignadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PropiedadesAsignadasLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(PropAsign, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel4.add(PropiedadesAsignadas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 110, 100));

        PropiedadesVendidas.setBackground(new java.awt.Color(0, 204, 204));
        PropiedadesVendidas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PropiedadesVendidasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PropiedadesVendidasMouseExited(evt);
            }
        });

        PropVendidas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PropVendidas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/buscar.png"))); // NOI18N
        PropVendidas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PropVendidas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PropVendidasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PropVendidasMouseExited(evt);
            }
        });

        javax.swing.GroupLayout PropiedadesVendidasLayout = new javax.swing.GroupLayout(PropiedadesVendidas);
        PropiedadesVendidas.setLayout(PropiedadesVendidasLayout);
        PropiedadesVendidasLayout.setHorizontalGroup(
            PropiedadesVendidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PropiedadesVendidasLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(PropVendidas, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        PropiedadesVendidasLayout.setVerticalGroup(
            PropiedadesVendidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PropiedadesVendidasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PropVendidas, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel4.add(PropiedadesVendidas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 110, 90));

        ExitPanel1.setBackground(new java.awt.Color(0, 204, 204));

        Exit3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Exit3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/cerrar-sesion.png"))); // NOI18N
        Exit3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Exit3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Exit3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Exit3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Exit3MouseExited(evt);
            }
        });

        javax.swing.GroupLayout ExitPanel1Layout = new javax.swing.GroupLayout(ExitPanel1);
        ExitPanel1.setLayout(ExitPanel1Layout);
        ExitPanel1Layout.setHorizontalGroup(
            ExitPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
            .addGroup(ExitPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ExitPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Exit3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        ExitPanel1Layout.setVerticalGroup(
            ExitPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(ExitPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ExitPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Exit3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel4.add(ExitPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 570, 110, -1));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 0, 110, 700));

        Real4.setFont(new java.awt.Font("British Shorthair", 0, 150)); // NOI18N
        Real4.setForeground(new java.awt.Color(0, 0, 0));
        Real4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Real4.setText("Real");
        jPanel2.add(Real4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 310, 240));

        State1.setFont(new java.awt.Font("Neo Sans Std", 1, 120)); // NOI18N
        State1.setForeground(new java.awt.Color(0, 0, 0));
        State1.setText("Estate");
        jPanel2.add(State1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, 370, -1));

        ListPanel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        ListPanel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/MainScreen_House2.png"))); // NOI18N
        jPanel2.add(ListPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 0, 650, 700));

        SmallHouse1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/MainScreen_House2(Small).png"))); // NOI18N
        jPanel2.add(SmallHouse1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 390, 110, 120));

        Administrador1.setFont(new java.awt.Font("Neo Sans Std", 1, 80)); // NOI18N
        Administrador1.setForeground(new java.awt.Color(204, 204, 204));
        Administrador1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Administrador1.setText("Vendedor");
        Administrador1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel2.add(Administrador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 560, 590, 110));

        javax.swing.GroupLayout MainScreen_VendedorLayout = new javax.swing.GroupLayout(MainScreen_Vendedor.getContentPane());
        MainScreen_Vendedor.getContentPane().setLayout(MainScreen_VendedorLayout);
        MainScreen_VendedorLayout.setHorizontalGroup(
            MainScreen_VendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        MainScreen_VendedorLayout.setVerticalGroup(
            MainScreen_VendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 675, Short.MAX_VALUE)
        );

        MainScreen_Admin2.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Line2.setBackground(new java.awt.Color(102, 204, 0));
        Line2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel5.add(Line2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 40));

        Layer2.setBackground(new java.awt.Color(102, 204, 0));
        Layer2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Indicator2.setBackground(new java.awt.Color(0, 0, 0));
        Indicator2.setFont(new java.awt.Font("Neo Sans Std", 0, 60)); // NOI18N
        Indicator2.setForeground(new java.awt.Color(255, 255, 255));
        Indicator2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Layer2.add(Indicator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 510, 130));

        jPanel5.add(Layer2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 390, 510, 120));

        jPanel6.setBackground(new java.awt.Color(102, 204, 0));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        OptionPanel2.setBackground(new java.awt.Color(102, 204, 0));
        OptionPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                OptionPanel2MouseExited(evt);
            }
        });

        Options2.setBackground(new java.awt.Color(255, 255, 255));
        Options2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Options2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/Option_Menu.png"))); // NOI18N
        Options2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Options2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Options2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Options2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Options2MouseExited(evt);
            }
        });

        javax.swing.GroupLayout OptionPanel2Layout = new javax.swing.GroupLayout(OptionPanel2);
        OptionPanel2.setLayout(OptionPanel2Layout);
        OptionPanel2Layout.setHorizontalGroup(
            OptionPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, OptionPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Options2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        OptionPanel2Layout.setVerticalGroup(
            OptionPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OptionPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Options2, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel6.add(OptionPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 110, 90));

        MantenimientoPanel2.setBackground(new java.awt.Color(102, 204, 0));
        MantenimientoPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MantenimientoPanel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MantenimientoPanel2MouseExited(evt);
            }
        });

        Mantenimiento2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Mantenimiento2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/rebautizar.png"))); // NOI18N
        Mantenimiento2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Mantenimiento2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Mantenimiento2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Mantenimiento2MouseExited(evt);
            }
        });

        javax.swing.GroupLayout MantenimientoPanel2Layout = new javax.swing.GroupLayout(MantenimientoPanel2);
        MantenimientoPanel2.setLayout(MantenimientoPanel2Layout);
        MantenimientoPanel2Layout.setHorizontalGroup(
            MantenimientoPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Mantenimiento2, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
        );
        MantenimientoPanel2Layout.setVerticalGroup(
            MantenimientoPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MantenimientoPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Mantenimiento2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );

        jPanel6.add(MantenimientoPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 110, 80));

        Bitacora_Panel2.setBackground(new java.awt.Color(102, 204, 0));
        Bitacora_Panel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Bitacora_Panel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Bitacora_Panel2MouseExited(evt);
            }
        });

        Bitacora2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Bitacora2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/portapapeles.png"))); // NOI18N
        Bitacora2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Bitacora2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Bitacora2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Bitacora2MouseExited(evt);
            }
        });

        javax.swing.GroupLayout Bitacora_Panel2Layout = new javax.swing.GroupLayout(Bitacora_Panel2);
        Bitacora_Panel2.setLayout(Bitacora_Panel2Layout);
        Bitacora_Panel2Layout.setHorizontalGroup(
            Bitacora_Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
            .addGroup(Bitacora_Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Bitacora_Panel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Bitacora2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        Bitacora_Panel2Layout.setVerticalGroup(
            Bitacora_Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(Bitacora_Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Bitacora_Panel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Bitacora2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel6.add(Bitacora_Panel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 110, 100));

        Reportes_Panel2.setBackground(new java.awt.Color(102, 204, 0));
        Reportes_Panel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Reportes_Panel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Reportes_Panel2MouseExited(evt);
            }
        });

        Reportes2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Reportes2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/buscar.png"))); // NOI18N
        Reportes2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Reportes2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Reportes2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Reportes2MouseExited(evt);
            }
        });

        javax.swing.GroupLayout Reportes_Panel2Layout = new javax.swing.GroupLayout(Reportes_Panel2);
        Reportes_Panel2.setLayout(Reportes_Panel2Layout);
        Reportes_Panel2Layout.setHorizontalGroup(
            Reportes_Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Reportes_Panel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Reportes2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        Reportes_Panel2Layout.setVerticalGroup(
            Reportes_Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Reportes_Panel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Reportes2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel6.add(Reportes_Panel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 110, 90));

        ExitPanel2.setBackground(new java.awt.Color(102, 204, 0));

        Exit4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Exit4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/cerrar-sesion.png"))); // NOI18N
        Exit4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Exit4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Exit4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Exit4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Exit4MouseExited(evt);
            }
        });

        javax.swing.GroupLayout ExitPanel2Layout = new javax.swing.GroupLayout(ExitPanel2);
        ExitPanel2.setLayout(ExitPanel2Layout);
        ExitPanel2Layout.setHorizontalGroup(
            ExitPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
            .addGroup(ExitPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ExitPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Exit4, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        ExitPanel2Layout.setVerticalGroup(
            ExitPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(ExitPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ExitPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Exit4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel6.add(ExitPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 570, 110, -1));

        jPanel5.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 0, 110, 700));

        Real5.setFont(new java.awt.Font("British Shorthair", 0, 150)); // NOI18N
        Real5.setForeground(new java.awt.Color(0, 0, 0));
        Real5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Real5.setText("Real");
        jPanel5.add(Real5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 310, 240));

        State2.setFont(new java.awt.Font("Neo Sans Std", 1, 120)); // NOI18N
        State2.setForeground(new java.awt.Color(0, 0, 0));
        State2.setText("Estate");
        jPanel5.add(State2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, 370, -1));

        ListPanel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        ListPanel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/MainScreen_House2.png"))); // NOI18N
        jPanel5.add(ListPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 0, 650, 700));

        SmallHouse2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/MainScreen_House2(Small).png"))); // NOI18N
        jPanel5.add(SmallHouse2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 390, 110, 120));

        Administrador2.setFont(new java.awt.Font("Neo Sans Std", 1, 80)); // NOI18N
        Administrador2.setForeground(new java.awt.Color(204, 204, 204));
        Administrador2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Administrador2.setText("Administrador");
        Administrador2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel5.add(Administrador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 560, 590, 110));

        javax.swing.GroupLayout MainScreen_Admin2Layout = new javax.swing.GroupLayout(MainScreen_Admin2.getContentPane());
        MainScreen_Admin2.getContentPane().setLayout(MainScreen_Admin2Layout);
        MainScreen_Admin2Layout.setHorizontalGroup(
            MainScreen_Admin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        MainScreen_Admin2Layout.setVerticalGroup(
            MainScreen_Admin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 675, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Fondo.setBackground(new java.awt.Color(255, 255, 255));
        Fondo.setForeground(new java.awt.Color(255, 255, 255));
        Fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Real_Estate.setBackground(new java.awt.Color(255, 255, 255));
        Real_Estate.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Dreams.setFont(new java.awt.Font("British Shorthair", 0, 80)); // NOI18N
        Dreams.setForeground(new java.awt.Color(0, 0, 0));
        Dreams.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Dreams.setText("dreams");
        Real_Estate.add(Dreams, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, 280, -1));

        Discover.setFont(new java.awt.Font("Neo Sans Std", 0, 30)); // NOI18N
        Discover.setForeground(new java.awt.Color(0, 153, 51));
        Discover.setText("Discover the House of your...");
        Real_Estate.add(Discover, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        Real.setFont(new java.awt.Font("British Shorthair", 1, 110)); // NOI18N
        Real.setForeground(new java.awt.Color(0, 0, 0));
        Real.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Real.setText("Real");
        Real_Estate.add(Real, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 240, -1));

        Estate.setFont(new java.awt.Font("Neo Sans Std", 1, 100)); // NOI18N
        Estate.setForeground(new java.awt.Color(102, 204, 0));
        Estate.setText("Estate");
        Real_Estate.add(Estate, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(153, 153, 153));
        Real_Estate.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 550, 20));

        Fondo.add(Real_Estate, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 590, 380));

        DeNuevo.setFont(new java.awt.Font("British Shorthair", 0, 70)); // NOI18N
        DeNuevo.setForeground(new java.awt.Color(51, 153, 0));
        DeNuevo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DeNuevo.setText("de nuevo!");
        Fondo.add(DeNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 100, 380, 120));

        Bienvenido.setBackground(new java.awt.Color(0, 0, 0));
        Bienvenido.setFont(new java.awt.Font("Neo Sans Std", 1, 48)); // NOI18N
        Bienvenido.setForeground(new java.awt.Color(51, 51, 51));
        Bienvenido.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Bienvenido.setText("BIENVENIDO");
        Fondo.add(Bienvenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 90, 390, 70));

        User.setFont(new java.awt.Font("Neo Sans Std Light", 0, 24)); // NOI18N
        User.setForeground(new java.awt.Color(51, 51, 51));
        User.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        User.setText("USERNAME");
        Fondo.add(User, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 180, 140, 40));

        Username.setFont(new java.awt.Font("Neo Sans Std Light", 0, 18)); // NOI18N
        Username.setText("Ingrese su Usuario");
        Username.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UsernameMouseClicked(evt);
            }
        });
        Username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernameActionPerformed(evt);
            }
        });
        Username.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                UsernameKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                UsernameKeyReleased(evt);
            }
        });
        Fondo.add(Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 210, 330, 40));

        Pass.setFont(new java.awt.Font("Neo Sans Std Light", 0, 24)); // NOI18N
        Pass.setForeground(new java.awt.Color(51, 51, 51));
        Pass.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Pass.setText("PASSWORD");
        Fondo.add(Pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 260, 140, 40));

        jPasswordField1.setFont(new java.awt.Font("Neo Sans Std Light", 0, 18)); // NOI18N
        jPasswordField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPasswordField1MouseClicked(evt);
            }
        });
        jPasswordField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordField1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jPasswordField1KeyReleased(evt);
            }
        });
        Fondo.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 290, 330, 40));

        LogIN.setBackground(new java.awt.Color(0, 0, 0));
        LogIN.setFont(new java.awt.Font("Neo Sans Std", 1, 28)); // NOI18N
        LogIN.setForeground(new java.awt.Color(0, 0, 0));
        LogIN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LogIN.setText("Log In");
        LogIN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Fondo.add(LogIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 360, 100, 50));

        Log.setBackground(new java.awt.Color(102, 204, 0));
        Log.setFont(new java.awt.Font("Neo Sans Std", 1, 24)); // NOI18N
        Log.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Log.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Log.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogMouseClicked(evt);
            }
        });
        Log.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogActionPerformed(evt);
            }
        });
        Fondo.add(Log, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 360, 330, 40));

        SignIn.setBackground(new java.awt.Color(0, 0, 0));
        SignIn.setFont(new java.awt.Font("Neo Sans Std", 1, 28)); // NOI18N
        SignIn.setForeground(new java.awt.Color(0, 0, 0));
        SignIn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SignIn.setText("Sign In");
        SignIn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Fondo.add(SignIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 430, 100, 50));

        Sign.setBackground(new java.awt.Color(204, 204, 204));
        Sign.setFont(new java.awt.Font("Neo Sans Std", 1, 24)); // NOI18N
        Sign.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Sign.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Sign.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SignMouseClicked(evt);
            }
        });
        Sign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignActionPerformed(evt);
            }
        });
        Fondo.add(Sign, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 430, 330, 40));

        Exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/cerrar-sesion.png"))); // NOI18N
        Exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ExitMouseExited(evt);
            }
        });
        Fondo.add(Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 500, -1, -1));

        Pass1.setFont(new java.awt.Font("Neo Sans Std Light", 0, 18)); // NOI18N
        Pass1.setForeground(new java.awt.Color(153, 153, 153));
        Pass1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Pass1.setText("No tienes cuenta? Entonces dale Sign In");
        Fondo.add(Pass1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 400, 330, 40));

        Mostrar_Pass.setFont(new java.awt.Font("Neo Sans Std Light", 0, 14)); // NOI18N
        Mostrar_Pass.setForeground(new java.awt.Color(102, 102, 102));
        Mostrar_Pass.setText("Mostrar Contraseña");
        Mostrar_Pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mostrar_PassActionPerformed(evt);
            }
        });
        Fondo.add(Mostrar_Pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 330, 150, 30));

        Login_Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/Login_Back.png"))); // NOI18N
        Login_Background.setOpaque(true);
        Fondo.add(Login_Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 90, 390, 400));

        Lines1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/Abstract Lines.png"))); // NOI18N
        Fondo.add(Lines1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, 660, 100));

        Lines2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/Abstract Lines.png"))); // NOI18N
        Fondo.add(Lines2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 480, 660, 100));

        Lines3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/Abstract Lines.png"))); // NOI18N
        Fondo.add(Lines3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-230, 480, 660, 100));

        Lines4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/Abstract Lines.png"))); // NOI18N
        Fondo.add(Lines4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-280, 0, 720, 100));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/Fondo.png"))); // NOI18N
        Fondo.add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 580));

        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LogActionPerformed

    private void UsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernameActionPerformed

    }//GEN-LAST:event_UsernameActionPerformed

    private void jPasswordField1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPasswordField1MouseClicked
        jPasswordField1.setText("");
    }//GEN-LAST:event_jPasswordField1MouseClicked

    private void UsernameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UsernameMouseClicked
        Username.setText("");
    }//GEN-LAST:event_UsernameMouseClicked

    private void SignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SignActionPerformed

    private void SignMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignMouseClicked
        Log_In log = new Log_In();

        log.setVisible(false);
        Sign_In.setVisible(true);
        Sign_In.setLocationRelativeTo(this);
        dispose();
    }//GEN-LAST:event_SignMouseClicked

    private void ExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseClicked
        int showConfirmDialog = JOptionPane.showConfirmDialog(rootPane, "Desea salir del Programa?", "WARNING!", JOptionPane.WARNING_MESSAGE);

        if (showConfirmDialog == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_ExitMouseClicked

    private void ExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseEntered

    }//GEN-LAST:event_ExitMouseEntered

    private void ExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseExited

    }//GEN-LAST:event_ExitMouseExited

    private void LogMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogMouseClicked
        String user = Username.getText();
        String pass = jPasswordField1.getText();

        if (user.equals("")) {
            JOptionPane.showMessageDialog(null, "Inserte su Nombre de Usuario Correctamente");
        } else if (pass.equals("")) {
            JOptionPane.showMessageDialog(null, "Inserte su Contraseña de Usuario Correctamente");
        } else if (user.equals("Admin") && pass.equals("12345")) {
            JOptionPane.showMessageDialog(null, "Succesfull Login", "Login de Administrador", JOptionPane.PLAIN_MESSAGE);
            isAdmin = true;

            Log_In sign = new Log_In();
            sign.setVisible(false);
            //MainScreen_Admin.setVisible(true);
            MainScreen_Vendedor.setVisible(true);
            dispose();
        } else if (User_Admin.iniciarSesion(user, pass)) {
            JOptionPane.showMessageDialog(null, "Successfull Login!");

            Log_In sign = new Log_In();
            MainScreen_Admin.setVisible(true);
            sign.setVisible(false);
            dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Usuario o Contraseña Incorectos \nIntentelo de Nuevo", "Incorrect User or Pass", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_LogMouseClicked

    private void Mostrar_PassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mostrar_PassActionPerformed
        if (Mostrar_Pass.isSelected()) {
            jPasswordField1.setEchoChar((char) 0);
        } else {
            jPasswordField1.setEchoChar('*');
        }
    }//GEN-LAST:event_Mostrar_PassActionPerformed

    private void Username1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Username1MouseClicked
        Username.setText("");
    }//GEN-LAST:event_Username1MouseClicked

    private void Username1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Username1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Username1ActionPerformed

    private void jPasswordField2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPasswordField2MouseClicked
        jPasswordField1.setText("");
    }//GEN-LAST:event_jPasswordField2MouseClicked

    private void jPasswordField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField2ActionPerformed

    private void Sign1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Sign1MouseClicked
        Log_In log = new Log_In();
        log.setVisible(false);
        MainScreen_Admin.setVisible(true);
        dispose();
    }//GEN-LAST:event_Sign1MouseClicked

    private void Sign1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sign1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Sign1ActionPerformed

    private void Mostrar_Pass1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mostrar_Pass1ActionPerformed
        if (Mostrar_Pass.isSelected()) {
            jPasswordField1.setEchoChar((char) 0);
        } else {
            jPasswordField1.setEchoChar('*');
        }
    }//GEN-LAST:event_Mostrar_Pass1ActionPerformed

    private void ArrowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ArrowMouseClicked
        Log_In login = new Log_In();

        Sign_In.setVisible(false);
        login.setVisible(true);

        login.setLocationRelativeTo(this);
        dispose();
    }//GEN-LAST:event_ArrowMouseClicked

    private void Pass2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pass2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Pass2MouseClicked

    private void OptionsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OptionsMouseClicked
        boolean isVisible = Mantenimiento.isVisible() || Bitacora.isVisible() || Reportes.isVisible();

        Mantenimiento.setVisible(!isVisible);
        Bitacora.setVisible(!isVisible);
        Reportes.setVisible(!isVisible);
    }//GEN-LAST:event_OptionsMouseClicked

    private void OptionsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OptionsMouseEntered
        OptionPanel.setBackground(new Color(0, 100, 0));
        Indicator.setText("OPCIONES");
    }//GEN-LAST:event_OptionsMouseEntered

    private void OptionsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OptionsMouseExited
        OptionPanel.setBackground(null);
        Indicator.setText("");

    }//GEN-LAST:event_OptionsMouseExited

    private void OptionPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OptionPanelMouseExited
        //OptionPanel.setBackground(null);
    }//GEN-LAST:event_OptionPanelMouseExited

    private void MantenimientoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MantenimientoMouseEntered
        MantenimientoPanel.setBackground(new Color(0, 100, 0));
        Indicator.setText("MANTENIMIENTO");
    }//GEN-LAST:event_MantenimientoMouseEntered

    private void MantenimientoPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MantenimientoPanelMouseEntered
        MantenimientoPanel.setBackground(null);
        Indicator.setText("");
    }//GEN-LAST:event_MantenimientoPanelMouseEntered

    private void MantenimientoPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MantenimientoPanelMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_MantenimientoPanelMouseExited

    private void Bitacora_PanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Bitacora_PanelMouseEntered

    }//GEN-LAST:event_Bitacora_PanelMouseEntered

    private void Bitacora_PanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Bitacora_PanelMouseExited

    }//GEN-LAST:event_Bitacora_PanelMouseExited

    private void Reportes_PanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Reportes_PanelMouseEntered

    }//GEN-LAST:event_Reportes_PanelMouseEntered

    private void Reportes_PanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Reportes_PanelMouseExited

    }//GEN-LAST:event_Reportes_PanelMouseExited

    private void Exit2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Exit2MouseClicked
        int showConfirmDialog = JOptionPane.showConfirmDialog(rootPane, "Desea salir del Programa?", "WARNING!", JOptionPane.WARNING_MESSAGE);

        if (showConfirmDialog == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_Exit2MouseClicked

    private void Exit2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Exit2MouseEntered
        ExitPanel.setBackground(Color.RED);
        Indicator.setText("SALIR");

    }//GEN-LAST:event_Exit2MouseEntered

    private void Exit2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Exit2MouseExited
        ExitPanel.setBackground(null);
        Indicator.setText("");

    }//GEN-LAST:event_Exit2MouseExited

    private void jPasswordField2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField2KeyPressed


    }//GEN-LAST:event_jPasswordField2KeyPressed

    private void jPasswordField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField1KeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            String user = Username.getText();
            String pass = jPasswordField1.getText();

            if (user.equals("")) {
                JOptionPane.showMessageDialog(null, "Inserte su Nombre de Usuario Correctamente");
            } else if (pass.equals("")) {
                JOptionPane.showMessageDialog(null, "Inserte su Contraseña de Usuario Correctamente");
            } else if (user.equals("Admin") && pass.equals("12345")) {
                JOptionPane.showMessageDialog(null, "Succesfull Login", "Login de Administrador", JOptionPane.PLAIN_MESSAGE);
                isAdmin = true;

                Log_In sign = new Log_In();
                sign.setVisible(false);
                MainScreen_Admin.setVisible(true);
                dispose();
            } else if (User_Admin.iniciarSesion(user, pass)) {
                JOptionPane.showMessageDialog(null, "Successfull Login!");

                Log_In sign = new Log_In();
                MainScreen_Admin.setVisible(true);
                sign.setVisible(false);
                dispose();
            } else {
                JOptionPane.showMessageDialog(null, "Usuario o Contraseña Incorectos \nIntentelo de Nuevo", "Incorrect User or Pass", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_jPasswordField1KeyReleased

    private void MantenimientoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MantenimientoMouseExited
        MantenimientoPanel.setBackground(null);
        Indicator.setText("");
    }//GEN-LAST:event_MantenimientoMouseExited

    private void BitacoraMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BitacoraMouseEntered
        Bitacora_Panel.setBackground(new Color(0, 100, 0));
        Indicator.setText("BITÁCORA");
    }//GEN-LAST:event_BitacoraMouseEntered

    private void BitacoraMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BitacoraMouseExited
        Bitacora_Panel.setBackground(null);
        Indicator.setText("");
    }//GEN-LAST:event_BitacoraMouseExited

    private void ReportesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReportesMouseEntered
        Reportes_Panel.setBackground(new Color(0, 100, 0));
        Indicator.setText("REPORTES");
    }//GEN-LAST:event_ReportesMouseEntered

    private void ReportesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReportesMouseExited
        Reportes_Panel.setBackground(null);
        Indicator.setText("");
    }//GEN-LAST:event_ReportesMouseExited

    private void UsernameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_UsernameKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_TAB) {
            jPasswordField1.setText("");
        }
    }//GEN-LAST:event_UsernameKeyPressed

    private void UsernameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_UsernameKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_TAB) {
            jPasswordField1.setText("");
        }
    }//GEN-LAST:event_UsernameKeyReleased

    private void jPasswordField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField1KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_TAB) {
            jPasswordField1.setText("");
        }
    }//GEN-LAST:event_jPasswordField1KeyPressed

    private void OptionsVendMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OptionsVendMouseClicked
        boolean isVisible = PropAsign.isVisible() || PropVendidas.isVisible();

        PropAsign.setVisible(!isVisible);
        PropVendidas.setVisible(!isVisible);
    }//GEN-LAST:event_OptionsVendMouseClicked

    private void OptionsVendMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OptionsVendMouseEntered
        OptionVendedor.setBackground(new Color(30, 30, 150));
        Indicator1.setText("OPCIONES");
    }//GEN-LAST:event_OptionsVendMouseEntered

    private void OptionsVendMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OptionsVendMouseExited
        OptionVendedor.setBackground(null);
        Indicator1.setText("");
    }//GEN-LAST:event_OptionsVendMouseExited

    private void OptionVendedorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OptionVendedorMouseExited
        //OptionPanel.setBackground(null);
    }//GEN-LAST:event_OptionVendedorMouseExited

    private void PropAsignMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PropAsignMouseEntered
        PropiedadesAsignadas.setBackground(new Color(30, 30, 150));
        Indicator1.setText("PROP. ASIGNADAS");
    }//GEN-LAST:event_PropAsignMouseEntered

    private void PropAsignMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PropAsignMouseExited
        PropiedadesAsignadas.setBackground(null);
        Indicator1.setText("");
    }//GEN-LAST:event_PropAsignMouseExited

    private void PropiedadesAsignadasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PropiedadesAsignadasMouseEntered

    }//GEN-LAST:event_PropiedadesAsignadasMouseEntered

    private void PropiedadesAsignadasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PropiedadesAsignadasMouseExited

    }//GEN-LAST:event_PropiedadesAsignadasMouseExited

    private void PropVendidasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PropVendidasMouseEntered
        PropiedadesVendidas.setBackground(new Color(30, 30, 150));
        Indicator1.setText("PROP. VENDIDAS");
    }//GEN-LAST:event_PropVendidasMouseEntered

    private void PropVendidasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PropVendidasMouseExited
        PropiedadesVendidas.setBackground(null);
        Indicator1.setText("");
    }//GEN-LAST:event_PropVendidasMouseExited

    private void PropiedadesVendidasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PropiedadesVendidasMouseEntered

    }//GEN-LAST:event_PropiedadesVendidasMouseEntered

    private void PropiedadesVendidasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PropiedadesVendidasMouseExited

    }//GEN-LAST:event_PropiedadesVendidasMouseExited

    private void Exit3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Exit3MouseClicked
        int showConfirmDialog = JOptionPane.showConfirmDialog(rootPane, "Desea salir del Programa?", "WARNING!", JOptionPane.WARNING_MESSAGE);

        if (showConfirmDialog == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_Exit3MouseClicked

    private void Exit3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Exit3MouseEntered
        ExitPanel1.setBackground(Color.RED);
        Indicator1.setText("SALIR");
    }//GEN-LAST:event_Exit3MouseEntered

    private void Exit3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Exit3MouseExited
        ExitPanel1.setBackground(null);
        Indicator1.setText("");
    }//GEN-LAST:event_Exit3MouseExited

    private void Options2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Options2MouseClicked
        boolean isVisible = Mantenimiento.isVisible() || Bitacora.isVisible() || Reportes.isVisible();

        Mantenimiento.setVisible(!isVisible);
        Bitacora.setVisible(!isVisible);
        Reportes.setVisible(!isVisible);
    }//GEN-LAST:event_Options2MouseClicked

    private void Options2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Options2MouseEntered
        OptionPanel.setBackground(new Color(0, 100, 0));
        Indicator.setText("OPCIONES");
    }//GEN-LAST:event_Options2MouseEntered

    private void Options2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Options2MouseExited
        OptionPanel.setBackground(null);
        Indicator.setText("");
    }//GEN-LAST:event_Options2MouseExited

    private void OptionPanel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OptionPanel2MouseExited
        //OptionPanel.setBackground(null);
    }//GEN-LAST:event_OptionPanel2MouseExited

    private void Mantenimiento2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Mantenimiento2MouseEntered
        MantenimientoPanel.setBackground(new Color(0, 100, 0));
        Indicator.setText("MANTENIMIENTO");
    }//GEN-LAST:event_Mantenimiento2MouseEntered

    private void Mantenimiento2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Mantenimiento2MouseExited
        MantenimientoPanel.setBackground(null);
        Indicator.setText("");
    }//GEN-LAST:event_Mantenimiento2MouseExited

    private void MantenimientoPanel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MantenimientoPanel2MouseEntered
        MantenimientoPanel.setBackground(null);
        Indicator.setText("");
    }//GEN-LAST:event_MantenimientoPanel2MouseEntered

    private void MantenimientoPanel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MantenimientoPanel2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_MantenimientoPanel2MouseExited

    private void Bitacora2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Bitacora2MouseEntered
        Bitacora_Panel.setBackground(new Color(0, 100, 0));
        Indicator.setText("BITÁCORA");
    }//GEN-LAST:event_Bitacora2MouseEntered

    private void Bitacora2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Bitacora2MouseExited
        Bitacora_Panel.setBackground(null);
        Indicator.setText("");
    }//GEN-LAST:event_Bitacora2MouseExited

    private void Bitacora_Panel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Bitacora_Panel2MouseEntered

    }//GEN-LAST:event_Bitacora_Panel2MouseEntered

    private void Bitacora_Panel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Bitacora_Panel2MouseExited

    }//GEN-LAST:event_Bitacora_Panel2MouseExited

    private void Reportes2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Reportes2MouseEntered
        Reportes_Panel.setBackground(new Color(0, 100, 0));
        Indicator.setText("REPORTES");
    }//GEN-LAST:event_Reportes2MouseEntered

    private void Reportes2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Reportes2MouseExited
        Reportes_Panel.setBackground(null);
        Indicator.setText("");
    }//GEN-LAST:event_Reportes2MouseExited

    private void Reportes_Panel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Reportes_Panel2MouseEntered

    }//GEN-LAST:event_Reportes_Panel2MouseEntered

    private void Reportes_Panel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Reportes_Panel2MouseExited

    }//GEN-LAST:event_Reportes_Panel2MouseExited

    private void Exit4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Exit4MouseClicked
        int showConfirmDialog = JOptionPane.showConfirmDialog(rootPane, "Desea salir del Programa?", "WARNING!", JOptionPane.WARNING_MESSAGE);

        if (showConfirmDialog == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_Exit4MouseClicked

    private void Exit4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Exit4MouseEntered
        ExitPanel.setBackground(Color.RED);
        Indicator.setText("SALIR");
    }//GEN-LAST:event_Exit4MouseEntered

    private void Exit4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Exit4MouseExited
        ExitPanel.setBackground(null);
        Indicator.setText("");
    }//GEN-LAST:event_Exit4MouseExited

    /**
     * @param args the command line arguments
     */
    public void MainScreen() {
        getContentPane().setPreferredSize(Toolkit.getDefaultToolkit().getScreenSize());
        setResizable(false);
        show();
        setLocationRelativeTo(null);
        this.setTitle("Teoría de Base de Datos I");
        Image icono = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("pics/Tiger.jpg"));
        this.setIconImage(icono);
        this.pack();

        Mantenimiento.setVisible(false);
        Bitacora.setVisible(false);
        Reportes.setVisible(false);
        
        PropAsign.setVisible(false);
        PropVendidas.setVisible(false);

        MainScreen_Admin.setExtendedState(MAXIMIZED_BOTH);
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Log_In.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Log_In.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Log_In.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Log_In.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Log_In().setVisible(true);
            }
        });
    }

    boolean isAdmin = false;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Administrador;
    private javax.swing.JLabel Administrador1;
    private javax.swing.JLabel Administrador2;
    private javax.swing.JLabel Arrow;
    private javax.swing.JLabel Background;
    private javax.swing.JLabel Background1;
    private javax.swing.JLabel Bienvenido;
    private javax.swing.JLabel Bienvenido1;
    private javax.swing.JLabel Bitacora;
    private javax.swing.JLabel Bitacora2;
    private javax.swing.JPanel Bitacora_Panel;
    private javax.swing.JPanel Bitacora_Panel2;
    private javax.swing.JLabel DeNuevo;
    private javax.swing.JLabel Discover;
    private javax.swing.JLabel Discover1;
    private javax.swing.JLabel Dreams;
    private javax.swing.JLabel Dreams1;
    private javax.swing.JLabel Estate;
    private javax.swing.JLabel Estate1;
    private javax.swing.JLabel Exit;
    private javax.swing.JLabel Exit2;
    private javax.swing.JLabel Exit3;
    private javax.swing.JLabel Exit4;
    private javax.swing.JPanel ExitPanel;
    private javax.swing.JPanel ExitPanel1;
    private javax.swing.JPanel ExitPanel2;
    private javax.swing.JPanel Fondo;
    private javax.swing.JPanel Fondo1;
    private javax.swing.JLabel Indicator;
    private javax.swing.JLabel Indicator1;
    private javax.swing.JLabel Indicator2;
    private javax.swing.JPanel Layer;
    private javax.swing.JPanel Layer1;
    private javax.swing.JPanel Layer2;
    private javax.swing.JPanel Line;
    private javax.swing.JPanel Line1;
    private javax.swing.JPanel Line2;
    private javax.swing.JLabel Lines1;
    private javax.swing.JLabel Lines2;
    private javax.swing.JLabel Lines3;
    private javax.swing.JLabel Lines4;
    private javax.swing.JLabel Lines5;
    private javax.swing.JLabel Lines6;
    private javax.swing.JLabel Lines7;
    private javax.swing.JLabel Lines8;
    private javax.swing.JLabel ListPanel;
    private javax.swing.JLabel ListPanel1;
    private javax.swing.JLabel ListPanel2;
    private javax.swing.JButton Log;
    private javax.swing.JLabel LogIN;
    private javax.swing.JLabel LogIN1;
    private javax.swing.JLabel Login_Background;
    private javax.swing.JLabel Login_Background1;
    private javax.swing.JFrame MainScreen_Admin;
    private javax.swing.JFrame MainScreen_Admin2;
    private javax.swing.JFrame MainScreen_Vendedor;
    private javax.swing.JLabel Mantenimiento;
    private javax.swing.JLabel Mantenimiento2;
    private javax.swing.JPanel MantenimientoPanel;
    private javax.swing.JPanel MantenimientoPanel2;
    private javax.swing.JCheckBox Mostrar_Pass;
    private javax.swing.JCheckBox Mostrar_Pass1;
    private javax.swing.JPanel OptionPanel;
    private javax.swing.JPanel OptionPanel2;
    private javax.swing.JPanel OptionVendedor;
    private javax.swing.JLabel Options;
    private javax.swing.JLabel Options2;
    private javax.swing.JLabel OptionsVend;
    private javax.swing.JLabel Pass;
    private javax.swing.JLabel Pass1;
    private javax.swing.JLabel Pass2;
    private javax.swing.JLabel PropAsign;
    private javax.swing.JLabel PropVendidas;
    private javax.swing.JPanel PropiedadesAsignadas;
    private javax.swing.JPanel PropiedadesVendidas;
    private javax.swing.JLabel Real;
    private javax.swing.JLabel Real1;
    private javax.swing.JLabel Real3;
    private javax.swing.JLabel Real4;
    private javax.swing.JLabel Real5;
    private javax.swing.JPanel Real_Estate;
    private javax.swing.JPanel Real_Estate1;
    private javax.swing.JLabel Reportes;
    private javax.swing.JLabel Reportes2;
    private javax.swing.JPanel Reportes_Panel;
    private javax.swing.JPanel Reportes_Panel2;
    private javax.swing.JButton Sign;
    private javax.swing.JButton Sign1;
    private javax.swing.JLabel SignIn;
    private javax.swing.JFrame Sign_In;
    private javax.swing.JLabel SmallHouse;
    private javax.swing.JLabel SmallHouse1;
    private javax.swing.JLabel SmallHouse2;
    private javax.swing.JLabel State;
    private javax.swing.JLabel State1;
    private javax.swing.JLabel State2;
    private javax.swing.JLabel TXT_Abajo;
    private javax.swing.JLabel User;
    private javax.swing.JLabel User1;
    private javax.swing.JTextField Username;
    private javax.swing.JTextField Username1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
